apiVersion: v1
kind: ConfigMap
metadata:
  name: article-config
data:
  mysql_host: mysql-svc
  mysql_port: "3306"
  mysql_dbname: appdb
---
apiVersion: v1
kind: Secret
metadata:
  name: article-secrets
type: Opaque
data:
  mysql_rootpwd: cm9vdHBhc3M=
  mysql_username: YXBwdXNlcg==
  mysql_password: YXBwdXNlcnBhc3M=