services:
  article-db:
    image: mysql:8.1
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_USER=appuser
      - MYSQL_PASSWORD=appuserpass
      - MYSQL_DB=appdb
    ports:
      - "15432:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: